// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"오프닝스킵","status":true,"description":"Alternative menu screen layout.","parameters":{}},
{"name":"게임오버맵리로드","status":true,"description":"v1.01 게임 오버 후 마지막으로 저장한 게임을 로드합니다.","parameters":{}}
];
